# Generated by Django 2.2.2 on 2019-07-09 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=26)),
                ('primary_color', models.CharField(max_length=7)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
                ('pillar', models.CharField(choices=[('+', 'Safety'), ('Q', 'Quality'), ('D', 'Delivery'), ('C', 'Cost'), ('I', 'Involvement')], max_length=1)),
                ('danger', models.FloatField()),
                ('safe', models.FloatField()),
                ('frequency', models.IntegerField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='dashboards.Dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
                ('plot_type', models.CharField(choices=[('li', 'Connected Scatter Plot')], max_length=2)),
                ('color', models.CharField(max_length=7)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='dashboards.Kpi')),
            ],
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.FloatField()),
                ('value', models.FloatField(null=True)),
                ('date', models.CharField(max_length=10)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dashboards.Series')),
            ],
        ),
    ]
