# Generated by Django 2.2.2 on 2019-07-02 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='pillar',
            field=models.CharField(choices=[('+', 'Safety'), ('Q', 'Quality'), ('D', 'Delivery'), ('C', 'Cost'), ('I', 'Involvement')], max_length=1),
        ),
        migrations.AlterField(
            model_name='series',
            name='plot_type',
            field=models.CharField(choices=[('li', 'Connected Scatter Plot')], max_length=2),
        ),
    ]
