# Generated by Django 2.2.2 on 2019-07-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_auto_20190702_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dashboards.Dashboard'),
        ),
    ]
