# Generated by Django 2.2.2 on 2019-08-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20190712_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Monthly'), (1, 'Weekly'), (2, 'Bi-Weekly')]),
        ),
    ]
