# Generated by Django 2.2.2 on 2019-07-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20190705_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dashboards.Series'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='dashboards.Dashboard'),
        ),
        migrations.AlterField(
            model_name='series',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='dashboards.Kpi'),
        ),
    ]
