# Generated by Django 2.2.2 on 2019-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_auto_20190705_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
