# Generated by Django 2.2.2 on 2019-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_action_actiontable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontable',
            name='parent',
            field=models.IntegerField(null=True),
        ),
    ]
