# Generated by Django 2.2.2 on 2019-08-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_auto_20190806_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='leader',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='letter',
            field=models.CharField(choices=[('+', 'Safety'), ('Q', 'Quality'), ('D', 'Delivery'), ('C', 'Cost'), ('I', 'Involvement')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='problem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='root_cause',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='solution',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
