# Generated by Django 2.2.2 on 2019-07-05 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_auto_20190705_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
