# Generated by Django 2.2.2 on 2019-07-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_auto_20190705_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='date',
            field=models.DateField(default='000000'),
        ),
    ]
