# Generated by Django 2.2.2 on 2019-07-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_auto_20190705_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='date',
            field=models.CharField(max_length=8),
        ),
    ]
