# Generated by Django 2.2.2 on 2019-08-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_action_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_actions', to='dashboards.ActionTable'),
        ),
    ]
