# Generated by Django 2.2.2 on 2019-07-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_auto_20190705_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='date',
            new_name='dates',
        ),
    ]
