# Generated by Django 2.2.2 on 2019-08-14 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_auto_20190814_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
