# Generated by Django 2.2.2 on 2019-09-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_auto_20190814_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='danger',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='safe',
        ),
        migrations.AddField(
            model_name='kpi',
            name='danger_deviation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='kpi_type',
            field=models.IntegerField(choices=[(0, 'Deviation'), (1, 'Win-lose'), (2, 'Threshold')], default=0),
        ),
        migrations.AddField(
            model_name='kpi',
            name='safe_deviation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='threshold_type',
            field=models.IntegerField(choices=[(0, 'Greater Than'), (1, 'Less Than')], null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='warning_margin',
            field=models.FloatField(null=True),
        ),
    ]
