# Generated by Django 2.2.2 on 2019-09-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_auto_20190912_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='letter',
            field=models.CharField(choices=[('Plus', 'Safety'), ('Q', 'Quality'), ('D', 'Delivery'), ('C', 'Cost'), ('I', 'Involvement')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='pillar',
            field=models.CharField(choices=[('Plus', 'Safety'), ('Q', 'Quality'), ('D', 'Delivery'), ('C', 'Cost'), ('I', 'Involvement')], max_length=5),
        ),
    ]
