# Generated by Django 2.2.2 on 2019-09-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_auto_20190912_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='global_target',
            field=models.FloatField(null=True),
        ),
    ]
