# Generated by Django 2.2.2 on 2019-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0018_kpi_global_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='global_target',
            field=models.FloatField(default=None, null=True),
        ),
    ]
