# Generated by Django 2.2.2 on 2019-09-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0019_auto_20190913_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='leader',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
