# Generated by Django 2.2.2 on 2019-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0023_kpi_ispercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='leader',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='problem',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='root_cause',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='solution',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='actiontable',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='audit',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='unit',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='win',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='win',
            name='participants',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
