# Generated by Django 2.2.2 on 2019-09-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0024_auto_20190918_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='unit',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
