# Generated by Django 2.2.2 on 2019-09-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0025_auto_20190918_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
