# Generated by Django 2.2.2 on 2019-09-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0026_audit_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='date',
            new_name='end_date',
        ),
    ]
