# Generated by Django 2.2.2 on 2019-09-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0027_auto_20190920_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
