# Generated by Django 2.2.2 on 2019-09-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0028_heat'),
    ]

    operations = [
        migrations.AddField(
            model_name='heat',
            name='dashboard',
            field=models.ForeignKey(null=True,default=None, on_delete=django.db.models.deletion.CASCADE, related_name='heat', to='dashboards.Dashboard'),
            preserve_default=False,
        ),
    ]
