# Generated by Django 2.2.2 on 2019-09-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0029_heat_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heat',
            name='dashboard',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat', to='dashboards.Dashboard'),
        ),
    ]
