# Generated by Django 2.2.2 on 2019-09-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0031_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Dashboard',
            new_name='dashboard',
        ),
    ]
