# Generated by Django 2.2.2 on 2019-09-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0033_auto_20190927_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='dashboard',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='dashboards.Dashboard'),
        ),
        migrations.AddField(
            model_name='win',
            name='dashboard',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='dashboards.Dashboard'),
        ),
    ]
