# Generated by Django 2.2.2 on 2019-11-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0034_auto_20190930_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='end_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='start_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
