# Generated by Django 2.2.2 on 2019-11-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0035_auto_20191119_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
