# Generated by Django 2.2.2 on 2020-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0037_auto_20200120_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='plot_type',
            field=models.CharField(choices=[('li', 'line'), ('ar', 'area'), ('bar', 'bar'), ('sc', 'scatter')], max_length=3),
        ),
    ]
