# Generated by Django 2.2.2 on 2020-01-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0038_auto_20200120_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Monthly'), (1, 'Weekly'), (2, 'Bi-Weekly'), (3, 'Daily')]),
        ),
    ]
